use salary
repl all basic_pc with (basic/gross)*100 for gross <> 0
repl all hrent_pc with (hrent/gross)*100 for gross <> 0
repl all convy_pc with (convy/gross)*100 for gross <> 0
repl all medical_pc with (medical/gross)*100 for gross <> 0
repl all cma_pc with (cma/gross)*100 for gross <> 0
repl all pma_pc with (pma/gross)*100 for gross <> 0
repl all other_pc with (other/gross)*100 for gross <> 0
repl all special_pc with (special/gross)*100 for gross <> 0


